services:
  container1:
    image: akshita443/container1:latest
    ports:
      - "6000:6000"
    volumes:
      - ./:/data
    depends_on:
      - container2
    networks:
      - app-network

  container2:
    image: akshita443/container2:latest
    ports:
    - "5000:5000"
    volumes:
      - ./:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
